### ISSUE TITLE
Some reviews/comments

### ISSUE THREAD

**Issue by luongvo** [AVI5HEK/surveys#11]
Hi @AVI5HEK, I'm Lucas from Nimble. Nice to meet you here 👋 

I'll take care of reviewing your assignment and give you some feedback here from our side by opening issue tickets. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues.

Firstly, you're doing well, the build is running smoothly and has a good UI 👌 There are some good things we can see from your assignment project:
- Up to date tech-stack with Hilt, Navigation Component, Paging, ...
- MVVM architecture: looks good, there are still slight issues with package organization, component's relationship that I will explain more below.
- Good unit-test writing and covering
- Proguard applied

Here are some small issues from the project:
1. Why do we need to define [cast](https://github.com/AVI5HEK/surveys/blob/development/app/src/main/java/com/avi5hek/surveys/core/extension/Misc.kt#L3) extension while Kotlin already supported for nullable casting by `as?` operator. I saw somewhere you used this extension but somewhere not with `as?`. What is the intention here? 🤓 

2. [GetSurveys](https://github.com/AVI5HEK/surveys/blob/development/app/src/main/java/com/avi5hek/surveys/domain/interactor/GetSurveys.kt) should be named with UseCase postfix to reduce the confusion 🤔 

3. There are some API credentials inside the [SurveyTokenAuthenticator](https://github.com/AVI5HEK/surveys/blob/development/app/src/main/java/com/avi5hek/surveys/core/SurveyTokenAuthenticator.kt#L30-L32), why didn't we define those credentials in gradle same to `BASE_URL` as well?

4. There is confusion between data, domain, and presentation model classes. For example, I see many **Survey** models in the code and that made me confused about its usage until I realized you kept them in the same name. Should we make a small refactoring here to have postfix in the model name, e.g. `Response` postfix for data models, none for domain models, and `UiModel` postfix for presentation models? 💭 

5. Why do we need to keep [CircularProgressDialogFragment](https://github.com/AVI5HEK/surveys/blob/development/app/src/main/java/com/avi5hek/surveys/core/CircularProgressDialogFragment.kt#L9) as open?

6. You can remove the ExampleUnitTest classes to avoid noises

7. If you could have a small UI test with instrumentation setup and simple test cases that would be a plus, but perhaps not mandatory.

Any questions please don't hesitate to bump it up, happy coding 😺

**Comment by AVI5HEK** [comment]
Hello @luongvo , nice to meet you too. Thanks a lot for the compliments. You've asked some great questions. Here are my thoughts:

1. The `cast()` extension function was my personal invention to cast objects _particularly_ in an optional chain which is easier to write and also, readable at the same time. For example,  
    `(someObj as? SomeClass)?.doStuff()` can be written as follows:  
    `someObj.cast(SomeClass)?.doStuff()`

If the chain gets more complex, e.g.-  
`someObj.someProperty.let { it as? SomeClass }?.doStuff()` can be written as:

`someObj.someProperty.cast<SomeClass>()?.doStuff()`

If you take a look at the decompiled Java code, the complexity is similar. That being said, in some places, `cast()` and `as?` are interchangeable. For example, [here](https://github.com/AVI5HEK/surveys/blob/a34106f6cb7348242c1cef7e674e17d7a8772b5d/app/src/main/java/com/avi5hek/surveys/presentation/feature/main/SurveyListFragment.kt#L84), `cast()` adds no more benefits than `as?`. So, I kept it like that. 🤓 

2. That's a great suggestion. Actually, that's how I used them in my previous projects. But, for some use cases, the class name can be too long. For instance, consider this class name from a real project that I worked on: `RemoveMemberFromSiteUseCase`. Also, when there are a lot of use cases in the project, that postfix seems very repetitive. I realized that removing the postfix doesn't actually decrease the readability since once you get the hang of it, you'll understand right away when you encounter another use case class in the same project, especially if this naming scheme is only reserved for the use cases. 😉 
    
3. In my opinion, defining the credentials like `BASE_URL` wouldn't be a better solution either. Since the credentials are sensitive information, it shouldn't be shared publicly in the repository (even if the repository is private, this approach is not a good practice). It's better to keep them inside a file and load them from the file using a gradle script. The file can be shared among the contributors through a secure channel, not via Git. Since this is a demo project and as a standard approach you should get new tokens using a refresh token provided after a successful login, I intentionally omitted this part. I'll create a pull request moving the credentials to a file as described. ㊙️ 
    
4. That's a great suggestion. I would do something like that in a real project. For a reviewer to understand that the models actually represent the same thing, I kept the names the same and used import alias to resolve the import conflicts. I'll create a PR refactoring the names as you've suggested.
    
5. In my opinion, this shouldn't be an issue since the `DialogFragment` is now extendable. For example, we can inherit it in another class for a circular progress with a different style, like color, animation and whatnot.
    
6. Will do. 👍 
    
7. I _wanted_ to add a UI test but encountered a cryptic error while building the project. As the requirement document didn't ask for it and due to time constraints, I had to skip it. Now that you've asked, I'll try to resolve the issue and add it. 🙂

**Comment by AVI5HEK** [comment]
@luongvo 
Please check the linked pull requests to see the changes. Also, check email for the `authCredentials.properties` file.

**Comment by luongvo** [comment]
Good morning @AVI5HEK. Thanks for taking my feedback quite fast, that's great to speed up the process.

1. That's just my curious because from my view, it doesn't bring too much improvement, even from your example
```
someObj.someProperty.let { it as? SomeClass }?.doStuff() can be written as:

someObj.someProperty.cast<SomeClass>()?.doStuff()
```
we still are able to write it like this
```
(someObj.someProperty as? SomeClass)?.doStuff()
```
but well, it depends on the perspective of each person and not a big deal. I highly appreciate your thinking about finding and improving the code.

2. Agree with you about keeping UseCase postfix could make the name of class sometimes become too long. But I don't think that would be a problem. A long class name still better than a short class name with the class's header comment to explain what is the purpose of this class or why do we need this class... 

> Also, when there are a lot of use cases in the project, that postfix seems very repetitive

I don't think so, so why do we need to put `Service`, `Activity` or `Fragment` into those components? 🤓 

> you'll understand right away when you encounter another use case class in the same project

Not really, think about the case your team has more than 1 member then 1 ppl will work on each part of the project and they don't know exactly about another part of the project. So naming is important.

3. 
> In my opinion, defining the credentials like BASE_URL wouldn't be a better solution either. Since the credentials are sensitive information, it shouldn't be shared publicly in the repository (even if the repository is private, this approach is not a good practice).

Correct, it could be in git excluded properties file. You know what would be the best 👍 

5. Just my curious, that's ok

**Comment by AVI5HEK** [comment]
Good morning @luongvo . Thanks so much for the followup.
1. You're absolutely right about the fact that casting inside the parentheses is not necessarily less advantageous than the extension function. It's really a matter of personal preference. As a fan of fluent API, I use this function to _avoid_ placing the chain inside parentheses. When I'm in the flow, even CTRL+ALT+T -> 2 feels like a few extra steps. 😛

2. You've got some very good points there. I can't disagree. 👍
